### ISSUE TITLE
Ramaparts/Heroic <Vazruden's Mount>

### ISSUE THREAD

**Issue by Tafuna** [scriptdev2/scriptdev2#126]
npc=18432
Confirmed that he spams Fear on HC
I watched a Raid trying to kill him 3 times (i was reviving them after wipe)
Casted "Bellowing Roar" (spell=39427) 7 times in 12 seconds one after the other

https://github.com/scriptdev2/scriptdev2/blob/master/scripts/outland/hellfire_citadel/hellfire_ramparts/boss_nazan_and_vazruden.cpp#L111

**Comment by xfurry** [comment]
Is this still an issue, or may I close it?
