### ISSUE TITLE
Gyth - Knock Away

### ISSUE THREAD

**Issue by TheTrueAnimal** [scriptdev2/scriptdev2#127]
It seems like Gyth doesn't use the spell Knoch Away. Tested him for about 10 Minutes.

NPC: http://www.wowhead.com/npc=10339
Spell: http://www.wowhead.com/spell=10101
http://www.wowhead.com/spell=10101

**Comment by Schmoozerd** [comment]
Good catch.

SPELL_KNOCK_AWAY is not used in the script.
Can you research in which phase strting from when how frequently this spell should be used?

**Comment by TheTrueAnimal** [comment]
https://www.youtube.com/watch?v=SAOJIPvRpMM
