### ISSUE TITLE
Finkle Einhorn

### ISSUE THREAD

**Issue by TheTrueAnimal** [scriptdev2/scriptdev2#128]
The NPC should be spawned when you skin the Beast. At the moment he's automatically spawned when the Beast dies.

Finkle: http://www.wowhead.com/npc=10776
The Beast: http://www.wowhead.com/npc=10430
https://web.archive.org/web/20070812201411/http://wow.allakhazam.com/db/mob.html?wmob=10776

Classic.

**Comment by Rushor** [comment]
i think this can be done with:
https://github.com/cmangos/mangos-classic/blob/master/src/game/CreatureAI.h#L175

**Comment by Rushor** [comment]
sai script:

```sql
-- The Beast SAI
SET @ENTRY := 10430;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,36,0,100,0,0,0,0,0,12,10776,6,0,0,0,0,1,0,0,0,0,0,0,0,"The Beast - On Corpse Removed - Summon Creature 'Finkle Einhorn'");
```

can be converted to cai :)

**Comment by xfurry** [comment]
@Rushor I'm kindly asking you to convert it. :wink:

**Comment by Rushor** [comment]
```sql
DELETE FROM creature_ai_scripts WHERE `creature_id`=10776:
INSERT INTO creature_ai_scripts VALUES (NULL, '10430', '26', '0', '100', '0', '0', '0', '0', '0', '12', '10776', '0', '360000', '0', '0', '0', '0', '0', '0', '0', '0', 'The Beast - On Corpse Removed - Summon Creature 'Finkle Einhorn');
```

it's hard to check all these different wikis for this ai :/ 

used this now https://github.com/cmangos/issues/wiki/Creature_ai_scripts
you mentioned EVENT_T_CORPSE_REMOVED what eventid is this? is there probably a better wiki?

**Comment by xfurry** [comment]
We don't have the corpse removed event as far as I'm aware.
We need to understand if such a thing is required. Maybe poke @Schmoozerd and @X-Savior

**Comment by Schmoozerd** [comment]
hmm, skinning is likely a spell, so i am pretty confident that we can catch this with OnSpellHit.

**Comment by xfurry** [comment]
Yeah... but the problem is that there are many spells. Probably at least 6-7.

**Comment by Schmoozerd** [comment]
Well, this is true, but the non-leather-skinning spells with Effect Scinning should be no problem (as they cannot be applied to a normal dead beast anyways)

So i think if you check for the spell-effect this should be fine enough.

**Comment by xfurry** [comment]
Can we check the spell effect in eventAI? I think not...
Only the spell family.

**Comment by Schmoozerd** [comment]
I see.

Well, we could add the 3(wotlk) required skinning spells to EventAI and be done.
Or we can use SD2 InstanceData::OnCreatureDespawn(Creature*) to be done with it.

Both methods will do and are reasonable well for this case in my view
