### ISSUE TITLE
Mobs turn around when stunned

### ISSUE THREAD

**Issue by TheTrueAnimal** [scriptdev2/scriptdev2#132]
When you stun a target (e.ex. with gouge) it tourns around and seems to look into the opposite direction. This is a visual bug.

**Comment by Ulduar** [comment]
You're right, but you probably will be asked to create an issue in the kernel, so as responsible for this kernel.

**Comment by xfurry** [comment]
This problem has to be fixed in core.
I think @cyberium did some work on stun auras recently, so maybe he knows more.
