### ISSUE TITLE
wailing_caverns.cpp

### ISSUE THREAD

**Issue by Grz3s** [scriptdev2/scriptdev2#137]
Main Npc 3678 has texts wrongly set in gossips in both phases.
How he should work:
1st. Default
- cast buff - works fine
- missing text - should be 698  ... (now is wrongly set in second phase)

2nd: After killing all 4 bosses:
- he should start event - works fine
- text that is used is wrong - should be - 699.

Also:
script breaks... in final part: after first group of mobs spawn in water: (final boss never spawns)
- all spawned mobs should walk towards our npc... and they should attack him. (at the moment they spawn in water and do nothing).

all can be checked on this avi:
https://www.youtube.com/watch?v=Oa1Twtw7Id4
GL ;)

**Comment by evil-at-wow** [comment]
The fact that the final event isn't working properly is a core bug (see issue #16).

**Comment by Grz3s** [comment]
well still gossips can be corrected then ;)

**Comment by Dainara82** [comment]
takes a Chance that we can spawn the endboss from beginning the Event in the 1. Phase that the dungeon can be finished until the real Problem is fixed?

**Comment by Schmoozerd** [comment]
you could disable mmaps via config or such. but from sd2-view the encounter must be fine i think.

(of course except the gossip isses above)

**Comment by xfurry** [comment]
@Dainara82 in SD2 encounter works as expected.
This is a problem with mmaps, so you can just disable them for this instance.

**Comment by alexluana** [comment]
I can confirm the mmaps disable to work out

**Comment by xfurry** [comment]
Then we should poke @Cyberium. Maybe he knows more about this.
