### ISSUE TITLE
Rescue OOX-09/HL!

### ISSUE THREAD

**Issue by TheTrueAnimal** [scriptdev2/scriptdev2#140]
I made the quest yesterday with a lvl 60 Shaman. The first wave of three owlbeasts came and we killed them. As soon as they were dead, there came 3 owlbeasts again and when they died, there were three spawned again, I died, the chicken died and no more npc spawned. It seems like the script hang up or maybe the spawn was triggered again and again because the chicken ran back some meters after the fights and when it went on on its way it passed the trigger again?

http://www.wowhead.com/quest=836
http://www.wowhead.com/npc=7806

**Comment by Rushor** [comment]
thats because the chicken always runs back to waypoint xx on reset and therefore the summon of the owls happens again and again :/

**Comment by tkrokli** [comment]
"Why did the chicken :chicken: cross the road?" :smirk_cat:
