### ISSUE TITLE
The Beast: Missing spells

### ISSUE THREAD

**Issue by TheTrueAnimal** [scriptdev2/scriptdev2#141]
The Beast in UBRS seems to have problems with its spells. We were there with two chars (gms) and pulled the boss several times.

- it never used its charge
- it had a really HUGE hitbox
- at the first pull, it didn't use its flamebreak (i did not record this try)
- then it didn't use its immolate.

I recorded our test when i found out, that the boss doesn't use its spells as it should. In some fights it never used a spell, in the next fight it used the same spell as it should. 
https://www.youtube.com/watch?v=lQOXv5UYAOw&feature=youtu.be

The Beast: http://www.wowhead.com/npc=10430
https://www.youtube.com/watch?v=ohu6unEXygA
https://www.youtube.com/watch?v=8Eu0myyS6Ms
https://www.youtube.com/watch?v=gyE877c3CN8

**Comment by xfurry** [comment]
This is done in acid
```sql
-- The Beast (SD2 Backport)
('1043001','10430','11','0','100','2','0','0','0','0','11','15506','0','0','0','0','0','0','0','0','0','0','The Beast - Cast Immolate on Spawn'),
('1043002','10430','0','0','100','3','23000','23000','20000','20000','11','14100','0','0','0','0','0','0','0','0','0','0','The Beast - Cast Terrifying Roar'),
('1043003','10430','0','0','100','3','20000','20000','10000','10000','11','16785','0','0','0','0','0','0','0','0','0','0','The Beast - Cast Flamebreak'),
('1043004','10430','0','0','100','3','2000','5000','8000','10000','11','16788','4','0','0','0','0','0','0','0','0','0','The Beast - Cast Fireball'),
```

It looks fine from my side.

**Comment by TheTrueAnimal** [comment]
It seems like these two spells are missing:
http://www.wowhead.com/spell=16144
http://www.wowhead.com/spell=16636
You can see in the videos that the boss uses them. I don't know why they're not listed at wowhead.

Other sources: 
http://wow.gamepedia.com/The_Beast
http://hordeguides.de/Instanz/Classic/Boss/10430/Die-Bestie/index.htm (German)
http://www.wowdb.com/npcs/10430-the-beast#related:casts
http://www.wowwiki.com/The_Beast
http://www.almarsguides.com/wow/instances/ubrs.cfm  (seems like the information WHO it charges to is wrong)

And we still have the problems I've already listed:
We were there with two chars (gms) and pulled the boss several times.

- it never used its charge
- it had a really HUGE hitbox
- at the first pull, it didn't use its flamebreak (i did not record this try)
- then it didn't use its immolate.

I recorded our test when i found out, that the boss doesn't use its spells as it should. In some fights it never used a spell, in the next fight it used the same spell as it should. Although the datebase tells that everything is working as it should my videos shows that there's still some kind of bug.
https://www.youtube.com/watch?v=lQOXv5UYAOw&feature=youtu.be
