### ISSUE TITLE
A Crew Under Fire

### ISSUE THREAD

**Issue by TheTrueAnimal** [scriptdev2/scriptdev2#142]
Some waves of mobs should come but nothing happens.

Quest: http://www.wowhead.com/quest=3382/a-crew-under-fire

http://wow.gamepedia.com/Quest:A_Crew_Under_Fire
https://www.youtube.com/watch?v=boaWcT8DWUM
https://web.archive.org/web/20070410203849/http://wow.allakhazam.com/db/quest.html?wquest=3382  (seems like the NPCs should buff and heal players)
https://web.archive.org/web/20070706161307/http://www.thottbot.com/q3382

**Comment by xfurry** [comment]
Can be done using dbscripts I think.

**Comment by xfurry** [comment]
Fixed in https://github.com/unified-db/Database/commit/b8988654c9244d7908da1f462d2fd0ebb7099b24
