### ISSUE TITLE
Server Don't starting with ScriptDev2

### ISSUE THREAD

**Issue by Dainara82** [scriptdev2/scriptdev2#143]
Hi, after some weeks i can't start a new core with scriptdev2
my System is an Linux Debian Wheezy 64bit system   everything is up to date, i have an cmangos core rev 12851 everything above don't work with scriptdev2 i don't know why and i have no errors
when i start the mangosd the server stops at

---------------------------------------------------------------------------------
Initializing Scripting Library...

 MMM  MMM    MM
M  MM M  M  M  M
MM    M   M   M
 MMM  M   M  M
   MM M   M MMMM
MM  M M  M
 MMM  MMM  http://www.scriptdev2.com

SD2: Using configuration file /home/mangoswotlk/wotlk1/run/etc/scriptdev2.conf

Connected to MySQL database root@127.0.0.1:3306/ncf1682scriptdev2
MySQL client library: 5.5.41
MySQL server ver: 5.5.41-0+wheezy1
AUTOCOMMIT SUCCESSFULLY SET TO 1
Connected to MySQL database root@127.0.0.1:3306/ncf1682scriptdev2
MySQL client library: 5.5.41
MySQL server ver: 5.5.41-0+wheezy1
AUTOCOMMIT SUCCESSFULLY SET TO 1
SD2: ScriptDev2 database initialized.

---------------------------------------------------------------------------------------
so if i rename scriptdev2.conf    the server starting like a charm 
i test the db connection with root, its the same
in the old core it works everything fine
i think there must be an problem
does everyone can help?

**Comment by evil-at-wow** [comment]
That part of the log looks good. Then you should get a line saying something like this:
`Loading ScriptDev2 (for CMaNGOS xxxx+) Revision [yyyy] ...`

If this is really the end of your log, then something seems to go wrong when the scripting library is querying and showing its version. So let's see what we can find out about the problem.
 * Can you run the following query on your SD2 database - ncf1682scriptdev2 in your case according to the log above - and check that it returns a single line with a version?  
`SELECT version FROM sd2_db_version LIMIT 1;`
 * You say renaming your scriptdev2.conf makes the server start. Can you post the content of your scriptdev2.conf file please? Note: remove the database password!
 * In particular, the config file probably contains an entry for the error log file. Something like this:  `SD2ErrorLogFile = "SD2Errors.log"`.  
Does this file actually exist? Is it writable for the user that starts the server?

**Comment by Dainara82** [comment]
the end of the log i postet  is really the end of my log ^^

i connected to mysql and enter the code, i get the following information:
+----------------------------------+
| version                          |
+----------------------------------+
| ScriptDev2 (for CMaNGOS 12839+)  |
+----------------------------------+
1 row in set (0.00 sec)

here the config, i removed all lines with # 
[ScriptDev2Conf]
ConfVersion=2012112301
ScriptDev2DatabaseInfo     = "127.0.0.1;3306;myuser;mypassword;ncf1682scriptdev2"
SD2ErrorLogFile = "/home/mangoswotlk/wotlk1/run/log/SD2Errors.log"

the same config i have for the other core and worked fine

no log from scriptdev2 is there,
the logfile will create only if i rename the scriptdev2.conf
so the permissions are right everything is running from the same user "not root"

the DB does work fine with the older core, so with the DB is everything all right

**Comment by xfurry** [comment]
I'm not sure if I understand what is the issue.

**Comment by Dainara82** [comment]
i think it must be some change from scriptdev2 or the core, that the combination from both don't work under Linux, the compilling prozess workes without errors

**Comment by xfurry** [comment]
Well, I don't have Linux, so I can't test.
Can anybody else confirm this, or propose a solution?

**Comment by Dainara82** [comment]
ok i compilled it again, and now it works, i do this time something else i will tell it. But i think somewhat will kidding me, couse i think this can't be the mistake. (every time when i do this, i move the maps vmaps mmaps and dbc folder to a other place, than i erase everything from the old folder, clone everything into the new folder compile it fresh and move back the folders.) for all this i have write a script what worked fine bevore.
i have 2 wotlk Server with 2 Databases, but only one from it is running, couse while running the 1. server i can make the seond server fresh. after the second server and database fresh i can shutdown the 1. server and start the new server, so the server is downtime only for 1 minute.
the realmd and character database is the same, only the world and scriptdev2 database i have two from it
1 for wotlk1 and the other for wotlk2

ok this time i have shutdown the second server rename the complete folder erase everything from the 1. server do everything what stay in the script per hand  and add this command into the compil prozess -DPCH=1

so can tell me everyone why it worked now? it can't be the second server couse this is an seperatly folder with a own database and times bevore i have this error it worked. or changed someone something in the repositories? :)

i want to understand it why but i can't

**Comment by xfurry** [comment]
This issue is quite old and I think it has been resolved with the recent project merge.
Closed.
