### ISSUE TITLE
NPC loot display

### ISSUE THREAD

**Issue by TheTrueAnimal** [scriptdev2/scriptdev2#144]
A new bug:
When you attack an enemy its name becomes gray as if you aren't allowed to get loot. But you can loot it.

**Comment by evil-at-wow** [comment]
I believe this is a TBC core issue that I just fixed in cmangos/mangos-tbc@9c8a07f2b6.
If you're using Classic, it will get backported soon.

**Comment by xfurry** [comment]
then, can we close this?
