### ISSUE TITLE
q. Ambush At The Overlook

### ISSUE THREAD

**Issue by Grz3s** [scriptdev2/scriptdev2#146]
Ambush At The Overlook -- needs magic touch of sd2.

First .. lets look what needs to be done:
https://www.youtube.com/watch?v=efM47NBlNcs
https://www.youtube.com/watch?v=afjYPz4O_zA
.....
What i know so far:
After use main item:
we cast spell:
53061  + another one is triggered here 53063
mount for Scarlet Courier - 14583 (modelid)
-----
```sql
-- Scarlet Courier 
Delete from `creature_ai_scripts` where `creature_id`= 29076;
Insert into `creature_ai_scripts` values 
('2907601','29076','11','0','100','0','0','0','0','0','43','0','14583','0','1','-8000','0','0','0','0','0','0','Goliathon Shardling - mount and Say on spawn'),
('2907602','29076','4','0','100','0','0','0','0','0','43','0','0','0','0','0','0','0','0','0','0','0','Scarlet Courier - unmount on aggro');
UPDATE creature_template SET AIName='EventAI' WHERE `entry` = '29076'; 
DELETE FROM `creature_ai_texts` WHERE `entry` IN ('-8000','-8001');
INSERT into `creature_ai_texts` (`entry`,`content_default`,`sound`,`type`,`language`,`comment`,`emote`) VALUES
('-8000','Hrm, what a strange tree. I must investigate.','0','0','0','28897','0'),
('-8001','What\'s this!? This isn\'t a tree at all! Guards! Guards!','0','0','0','28897','0');
```
What needs to be done by sd2.

Courier after spawn should 'do' few steps towards tree... then say second text ... (unmount + despawn tree)
Also... 2nd avi shows... good thing...if we'll attack courier before... tree is despawned... (object will despawn after his death)
P.S .. got sniffs if u need tchem ofc;)
GL

**Comment by xfurry** [comment]
@Grz3s please add his mount in DB. Thanks
