### ISSUE TITLE
Fix for r3121_scriptdev2.sql

### ISSUE THREAD

**Issue by Tauriella** [scriptdev2/scriptdev2#148]
Fix:
Change gosip-texts to gossip_texts in the first Line
DELETE FROM gossip_texts WHERE entry IN (-3649014,-3649015,-3649016,-3649017);
INSERT INTO gossip_texts (entry,content_default,comment) VALUES
(-3649014,'We\'re ready. This time things will be different.','barrett GOSSIP_ITEM_BEAST_WIPE_START'),
(-3649015,'Now.','barrett GOSSIP_ITEM_JARAXXUS_WIPE_START'),
(-3649016,'We\'ll just have to improve our teamwork to match the two of them.','barrett GOSSIP_ITEM_TWINS_WIPE_INIT'),
(-3649017,'Just bring them out again, then watch.','barrett GOSSIP_ITEM_TWINS_WIPE_START');

**Comment by xfurry** [comment]
Already fixed in https://github.com/scriptdev2/scriptdev2/commit/293a42ee40dcd2a46fccf12d1fa838d357aafb26
