### ISSUE TITLE
Eye of Acherus

### ISSUE THREAD

**Issue by Grz3s** [scriptdev2/scriptdev2#149]
Hi
Eye of Acherus in ebon_hold.cpp
http://www.wowhead.com/npc=28511/eye-of-acherus
NPC takes wrong modelid2 = 25499 from creature_template...(should take modelid1 = 26320)
- I never saw any diff script with same situation happened. -- so i dont think that this is global problem for all creatures etc.. (maybe blizz did smth wrong... and after they changed his model by spell or smth else)
- i found in sniff spells -- that are server_side _spell and no idea what they do there ... 
I made simply (temp) fix for this: 
It may be not right... but lets use it until this mistery will be resolved (we all know ...it wont be anytime soon) 
```code
@@ -1244,10 +1244,11 @@ struct npc_eye_of_acherusAI : public ScriptedAI
         if (m_bIsInitialized)
             return;
 
         if (Player* pPlayer = m_creature->GetCharmerOrOwnerPlayerOrPlayerItself())
         {
+			m_creature->SetDisplayId(26320);                // HACK remove when correct modelid will be taken by core
             m_creature->SetPhaseMask(2, true);              // HACK remove when summon spells and auras are implemented properly in mangos
 
             DoScriptText(EMOTE_DESTIANTION, m_creature, pPlayer);
```
tested and works fine with nevest core and sd2

**Comment by Tauriella** [comment]
@Xfurry
Can you please add this fix in your git
thanks
