### ISSUE TITLE
Razorfen Downs: Gong Event

### ISSUE THREAD

**Issue by Rog360** [scriptdev2/scriptdev2#155]
Tuten'Kash [c7355] should be spawned by players on 3rd gong [Go148917], Here's a good video on it... :)

http://www.youtube.com/watch?v=bgXjlecqq1k

**Comment by xfurry** [comment]
I thought that we fixed this: https://github.com/scriptdev2/scriptdev2/commit/60d25551fa0320f18a6485c1211428cfeb4e6e7e

**Comment by Rog360** [comment]
Was real late when I checked this. I'll check it again and if any problems I'll get back to you... :)

**Comment by Rog360** [comment]
@xfurry  Is there and prerequisite to using the gong? I've searched google with no results... :(

**Comment by xfurry** [comment]
No.
You just need to click and the Gong shouldn't despawn (unfortunately, now it does).

**Comment by cala** [comment]
As Xfurry said, there is no prerequisite for using the gong the first time. The second and third time, the gong is unusable until all the spawned NPCs are killed.

@Rog360 I think your issue comes from the gameobject flags in PSMDB: the gong (ID 148917) has `flags = 16` which is "unusable by players", while UDB, YTDB, TBC-DB and Classic DB have `flag = 0`

**Comment by Rog360** [comment]
@cala  I changed the Gobject flags and checked all other settings and still got nothing. Does it work on classic? If so, I'll have to check this further. Thanks for the help... :)

**Comment by cala** [comment]
I'll test this to be 100% certain, but I'm pretty sure that I wrote the patch with Classic core, then checked that it also work fine with WotLK before pushing it. That's what I do, usually.

**Comment by cala** [comment]
Tested on Classic (sorry for the delay): it is working. The only issue I see is that the gong despawns and only reappears when ready to call for the next wave of monsters.

**Comment by xfurry** [comment]
@Rog360 is this still an issue, or can we close this?

**Comment by Rog360** [comment]
Still an issue. I've checked everything to the best of my knowledge and still can't get it to work. Cala says it works in classic. So, I'll check it over again against classic data and post back here asap... :)

@xfurry Only difference in GO template is Classic has data3 =196608. Tried it with no luck... :(

This is server log when I click the gong. May be of some use in finding the problem.

```
 2015-10-30 02:36:02 WORLD: Received opcode CMSG_GAMEOBJ_USE guid: Gameobject   (Entry: 148917 Guid: 20634)
 2015-10-30 02:36:02 Goober ScriptStart id 3130 for Gameobject (Entry: 148917 Guid: 20634)  (Used by Player Bagoflead (Guid: 7)).
 2015-10-30 02:36:02 WORLD: Received opcode CMSG_GAMEOBJ_REPORT_USE guid: Gameobject (Entry: 148917 Guid: 20634)
 2015-10-30 02:36:03 Player::UpdateItemDuration(1,0)
 2015-10-30 02:36:03 WORLD: Received opcode CMSG_TIME_SYNC_RESP: counter 1, client  ticks 49685204, time since last sync 9171
 2015-10-30 02:36:03  WORLD: Opcode CMSG_TIME_SYNC_RESP -- Our ticks: 49685251, diff  47, latency 0
 2015-10-30 02:36:03 Map::GetHitPosition vmaps corrects gained with static objects! new dest coords are X:2579.966309 Y:944.122986 Z:63.290199
 2015-10-30 02:36:03 Map::GetHitPosition vmaps corrects gained with static objects! new dest coords are X:2578.649170 Y:940.221313 Z:63.290199

 ERROR:HandleGameObjectUseOpcode: CMSG_GAMEOBJ_USE for despawned GameObject (Entry 148917), didn't expect this to happen.
```

**Comment by xfurry** [comment]
Try this:

``` sql
DELETE FROM `gameobject_template` WHERE (`entry`=148917);
INSERT INTO `gameobject_template` (`entry`, `type`, `displayId`, `name`, `IconName`, `castBarCaption`, `unk1`, `faction`, `flags`, `size`, `questItem1`, `questItem2`, `questItem3`, `questItem4`, `questItem5`, `questItem6`, `data0`, `data1`, `data2`, `data3`, `data4`, `data5`, `data6`, `data7`, `data8`, `data9`, `data10`, `data11`, `data12`, `data13`, `data14`, `data15`, `data16`, `data17`, `data18`, `data19`, `data20`, `data21`, `data22`, `data23`, `mingold`, `maxgold`, `ScriptName`) VALUES (148917, 10, 2372, 'Gong', '', '', '', 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 3130, 3000, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '');
```

and also update to latest core.
I guess it should work fine.

**Comment by xfurry** [comment]
@Rog360 which client version are you using?
I just tested on wotlk and it works fine.

If you have other version, the map might be different, hence we might need to change spawn coords.

**Comment by Rog360** [comment]
I'm using WotLK 3.3.5. If it's working on Classic and on UDB. It must be something in PSDB causing this issue. I'll keep looking... :)  You can close this issue, if you want, Since it's not an SD2 issue. If you can think of anything I maybe overlooking. I'll be glad to check it out... :)

**Comment by xfurry** [comment]
Check if your script is registered.
Meaning if you the event script is registered. 

``` sql
DELETE FROM scripted_event_id WHERE id=3130;
INSERT INTO scripted_event_id VALUES (3130, 'event_go_tutenkash_gong');
```

**Comment by Rog360** [comment]
Yes, It's added. Anything else you can think of?

**Comment by Rog360** [comment]
Nevermind I found it. One of the event npcs were spawned nearby. There by canceling the event... :)

You can close this one now... ;)
