### ISSUE TITLE
Add condition for Vezax Thrash in Ulduar.

### ISSUE THREAD

**Issue by Ulduar** [scriptdev2/scriptdev2#159]
``` diff
commit 13bac5ed2a14f4194eb1d7abdffe589b7cf6346b
Date:   Fri May 8 06:29:07 2015 +0600

    Add condition for Vezax Thrash in Ulduar.
    If Keeper encounter !=DONE, force despawn, if Keeper encounter ==DONE, respawn.

diff --git a/scripts/northrend/ulduar/ulduar/instance_ulduar.cpp b/scripts/northrend/ulduar/ulduar/instance_ulduar.cpp
index 53e02fc..9165e3e 100644
--- a/scripts/northrend/ulduar/ulduar/instance_ulduar.cpp
+++ b/scripts/northrend/ulduar/ulduar/instance_ulduar.cpp
@@ -290,7 +290,24 @@ void instance_ulduar::OnCreatureCreate(Creature* pCreature)
             else
                 m_vaporVezaxBunnyGuid = pCreature->GetObjectGuid();
             return;
-
+            // Should spawn only if Freya, Hodir, Thorim and Mimiron defeated.
+        case NPC_TWILIGHT_PYROMANCER:
+        case NPC_TWILIGHT_FROSTMAGE:
+        case NPC_TWILIGHT_SHADOWBLADE:
+        case NPC_TWILIGHT_ADHERENT:
+        case NPC_TWILIGHT_GUARDIAN:
+        case NPC_TWILIGHT_SLAYER:
+        case NPC_FACELESS_HORROR:
+            m_lVezaxThrashGuids.push_back(pCreature->GetObjectGuid());
+            if (m_auiEncounter[TYPE_MIMIRON] != DONE && m_auiEncounter[TYPE_HODIR] != DONE && m_auiEncounter[TYPE_THORIM] != DONE && m_auiEncounter[TYPE_FREYA] != DONE)
+                
+               for (GuidList::const_iterator itr = m_lVezaxThrashGuids.begin(); itr != m_lVezaxThrashGuids.end(); ++itr)
+               {
+                if (Creature* pVezaxThrash = instance->GetCreature(*itr))
+                    pVezaxThrash->ForceDespawn();
+               }
+             return;
+            
         default:
             return;
     }
@@ -455,6 +472,20 @@ void instance_ulduar::DoOpenMadnessDoorIfCan()
         DoUseDoorOrButton(GO_ANCIENT_GATE);
 }
 
+void instance_ulduar::DoRespawnVezaxThrashIfCan()
+{
+    if (m_auiEncounter[TYPE_MIMIRON] == DONE && m_auiEncounter[TYPE_HODIR] == DONE && m_auiEncounter[TYPE_THORIM] == DONE && m_auiEncounter[TYPE_FREYA] == DONE && m_auiEncounter[TYPE_VEZAX] != DONE)
+        
+        for (GuidList::const_iterator itr = m_lVezaxThrashGuids.begin(); itr != m_lVezaxThrashGuids.end(); ++itr)
+            {
+                if (Creature* pVezaxThrash = instance->GetCreature(*itr))
+                {
+                    if (!pVezaxThrash->isAlive())
+                        pVezaxThrash->Respawn();
+                }
+            }
+}
+
 void instance_ulduar::SetData(uint32 uiType, uint32 uiData)
 {
     switch (uiType)
@@ -637,6 +668,7 @@ void instance_ulduar::SetData(uint32 uiType, uint32 uiData)
 
                 SpawnFriendlyKeeper(NPC_KEEPER_MIMIRON);
                 DoOpenMadnessDoorIfCan();
+                DoRespawnVezaxThrashIfCan();
             }
             else if (uiData == IN_PROGRESS)
                 DoToggleGameObjectFlags(GO_MIMIRON_BUTTON, GO_FLAG_NO_INTERACT, true);
@@ -688,6 +720,7 @@ void instance_ulduar::SetData(uint32 uiType, uint32 uiData)
 
                 SpawnFriendlyKeeper(NPC_KEEPER_HODIR);
                 DoOpenMadnessDoorIfCan();
+                DoRespawnVezaxThrashIfCan();
             }
             else if (uiData == FAIL)
             {
@@ -728,6 +761,7 @@ void instance_ulduar::SetData(uint32 uiType, uint32 uiData)
 
                 SpawnFriendlyKeeper(NPC_KEEPER_THORIM);
                 DoOpenMadnessDoorIfCan();
+                DoRespawnVezaxThrashIfCan();
             }
             else if (uiData == FAIL)
             {
@@ -769,6 +803,7 @@ void instance_ulduar::SetData(uint32 uiType, uint32 uiData)
 
                 SpawnFriendlyKeeper(NPC_KEEPER_FREYA);
                 DoOpenMadnessDoorIfCan();
+                DoRespawnVezaxThrashIfCan();
             }
             break;
 
diff --git a/scripts/northrend/ulduar/ulduar/ulduar.h b/scripts/northrend/ulduar/ulduar/ulduar.h
index 1d6f789..4d48d74 100644
--- a/scripts/northrend/ulduar/ulduar/ulduar.h
+++ b/scripts/northrend/ulduar/ulduar/ulduar.h
@@ -176,6 +176,15 @@ enum
     NPC_VOICE_OF_YOGG           = 33280,
     NPC_OMINOUS_CLOUD           = 33292,
     NPC_GUARDIAN_OF_YOGG        = 33136,
+    
+    // General Vezax thrash
+    NPC_TWILIGHT_PYROMANCER     = 33820,
+    NPC_TWILIGHT_FROSTMAGE      = 33819,
+    NPC_TWILIGHT_SHADOWBLADE    = 33824,
+    NPC_TWILIGHT_ADHERENT       = 33818,
+    NPC_TWILIGHT_GUARDIAN       = 33822,
+    NPC_TWILIGHT_SLAYER         = 33823,
+    NPC_FACELESS_HORROR         = 33772,
 
     // Yogg Saron illusions actors
     NPC_YSERA                   = 33495,
@@ -594,6 +603,7 @@ class instance_ulduar : public ScriptedInstance, private DialogueHelper
         void DoSpawnHodirNpcs(Player* pSummoner);
         void DoOpenMadnessDoorIfCan();
         void DoCallLeviathanHelp();
+        void DoRespawnVezaxThrashIfCan();
 
         std::string m_strInstData;
         uint32 m_auiEncounter[MAX_ENCOUNTER];
@@ -629,6 +639,7 @@ class instance_ulduar : public ScriptedInstance, private DialogueHelper
         GuidList m_lLeftHandBunniesGuids;
         GuidList m_lRightHandBunniesGuids;
         GuidList m_lOminousCloudsGuids;
+        GuidList m_lVezaxThrashGuids;
         GuidSet m_sColossusGuidSet;
 };
 
```
http://www.ebon-flame.com/wiki/Ulduar_Trash#General_Vezax
Also need ( i don't know
``` QUOTE
This trash consists of four groups of humanoid Twilight Cultists, and three Faceless Ones. The first group, followed by the first Faceless One, are blocking the way into the Descend into Madness. The rest are arrayed inside the General's room.
```
It is necessary to check in to 10 and 25 people, there are different amounts of trash for humanoid (Faceless Horrors there are 3 and 10, and 25)
Why is this important? The room itself General, there are 3 pack trash and after the murder of two packs must be activated Faceless Horror and patrol room.

Simply put need to be extra formation guid list for trash in the room General.
P.S on future:
I'm not sure that my words will be confirmed by anyone, so as to such trifles few people pay attention)
But I do remember that it is, so as Ulduar crawled up and down!

**Comment by Ulduar** [comment]
@Xfurry, To answer your question (so-as the repository had to be removed in order to pullrequest able to send)
``` QUOTE
Why do you need exception for this? there are only one spell that will use this icon: 64169. The other two are not used by players.
``` 
63288 and 64169  should stack up to each other.
Why icon id? I wrote in a comment that there are still spells in Cata:
+ // Sanity Well (dummy) and Sanity Well (blessing), also (in Cataclysm Spirit Link Totem and Name: Blessing of the Grove)
Sanity Well, Spirit Link Totem, Blessing of the Grove it may happen that they are not on stack.

**Comment by xfurry** [comment]
I'm not sure if your logic is right or wrong but you can do this in creature_linking_template. You can see how it works in Molten Core.
Hence patch is not required.

**Comment by Ulduar** [comment]
``` QUOTE
I'm not sure if your logic is right or wrong but you can do this in creature_linking_template. You can see how it works in Molten Core.
```
Why do you close your issue, do not even read them fully.
These NPCs can not have 4 masters simultaneously. They spawn only if all 4 Guardian defeated. All 4 encounter == done, only spawn. Open the issue again please.

**Comment by xfurry** [comment]
Then your patch is clearly wrong. We don't despawn the creatures on create and respawn on some script event. If you really need to do that, then you need to summon the npcs.
However this isn't happening, as it doesn't appear in the sniff. The creatures are spawned by default from the first time the instance is loaded.

Anyway, you have a door that will block access to that area before the keeprers are done, so why bother...

**Comment by Ulduar** [comment]
``` QUOTE
Then your patch is clearly wrong. We don't despawn the creatures on create and respawn on some script event. If you really need to do that, then you need to summon the npcs.
```
And can sniff this information simply does not hit, you do not think about it?
``` QUOTE
However this isn't happening, as it doesn't appear in the sniff. The creatures are spawned by default from the first time the instance is loaded.
```
By default, they should not be. Do not believe me? Go on the off, kill Kologarn and go down - you do not see any trash. Then Defeat Hodir, Freya, Thorim and Mimiron, and return to this passage. Trash will appear!
``` QUOTE
Anyway, you have a door that will block access to that area before the keeprers are done, so why bother...
```
Because it blizzlike, in which me constantly poke. And even if it is a trifle, I would even realize it.

**Comment by xfurry** [comment]
> Go on the off, kill Kologarn and go down - you do not see General Vezax trash.

And how will you pass through the door, without defeating the keepers? In 3.x you can't do that.


> And can sniff this information simply does not hit, you do not think about it?

Sniffs are always correct. The behavior might have changed after 4.x
I will check again the 3.x sniff

> Because it blizzlike, in which me constantly poke

If it's blizzlike then it's fine.
But you have to think on the things which make sense from the priority point of view. Currently this doesn't have any negative impact on gameplay.
Anyway, **if** this is proved by sniff and **if** it's indeed blizzlike then we need a core feature that will spawn / load creatures inside an instance based on script conditions.
This might be useful for ICC instances as well.
However, the current patch is not acceptable. As I said, we don't despawn creatures on create and the respawn on some event.
Also it won't be correct, as those creatures have short respawn time, so in 1-2 hours will spawn again, without passing through the OnCreatureCreate function.

PS. I know that I tried to do this myself in the Nagrand outdoor pvp system. But I was pushed back by the core team due to the same reason. So you either have to summon the mobs, or change the core to load creatures on demand.

**Comment by Ulduar** [comment]
``` QUOTE
And how will you pass through the door, without defeating the keepers? 
```
Once at the forum, I raised the topic about M'uru and @Evil-at-wow  saved me (thanks for this) and corroborate my words! Here is the same case)
``` QUOTE
In 3.x you can't do that.
```
Also in 4.x, 5.x and 6.x. 
``` QUOTE
Sniffs are always correct. 
```
Maybe...
``` QUOTE
The behavior might have changed after 4.x
```
Only delete world state for Algalon.
``` QUOTE
If it's blizzlike then it's fine.
```
Blizzlike, Blizzard can confirm)
``` QUOTE
But you have to think on the things which make sense from the priority point of view. Currently this doesn't have any negative impact on gameplay.
```
``` QUOTE
This might be useful for ICC instances as well.
```
Maybe.
``` QUOTE
Anyway, if this is proved by sniff and if it's indeed blizzlike then we need a core feature that will spawn / load creatures inside an instance based on script conditions.
```
db_script_on_player_enter_map, db_script_on_creature_aggro, db_script_on_creature_evade, db_script_on_creature_despawn, CONDITION_INSTANCE_DATA, SCRIPT_COMMAND_RESPAWN - Yes, I will be with both hands only)
``` QUOTE
Also it won't be correct, as those creatures have short respawn time, so in 1-2 hours will spawn again, without passing through the OnCreatureCreate function.
```
Offe all trash tied to the bosses, somewhere along the guid (2 robot to Curator). If the boss is killed - the trash can not be spawn also can not respawn.

``` QUOTE
However, the current patch is not acceptable. As I said, we don't despawn creatures on create and the respawn on some event.
```
Thrash should despawn and respawn only if 4 Keeper == DONE.
I speak what I have seen with my own eyes.

**Comment by xfurry** [comment]
For M'uru it was a different issue, and in that case you were actually right. :wink: 

Let's discuss on IRC, after I'll check the sniff.

**Comment by Lumber-Jack-2** [comment]
so many word for nothing :D always nice to read those reports here xD

**Comment by xfurry** [comment]
> so many word for nothing

Why for nothing? I think that most of the requirements are already implemented.
