### ISSUE TITLE
Wailing Caverns: summoned creatures do not attack Disciple of Naralex

### ISSUE THREAD

**Issue by ike3** [scriptdev2/scriptdev2#16]
In waking Naralex event the adds are spawned around Disciple of Naralex but do not attack him. Final boss is not spawned. 
(Mangos master, wow 3.3.5a, UDB). Is this handled by ScriptDev2 scripts?

**Comment by r4z0r84** [comment]
They don't move towards you due to MMaps. change their range to shorter and they will attack him thus allowing the encounter to work as it should.
eg.

// Distance, Angle or Offset
static const float aSummonPositions[5][2] =
{
    {50.0f, -0.507f},                                       // First Raptors
    {53.0f, -0.603f},
    { 7.0f, 1.73f},                                         // Vipers
    {30.0f, 5.16f},                                         // Chamber
    {30.0f, 0.5901f}                                        // Mutanus
};

This works.

**Comment by Rushor** [comment]
```c++
summoned->AddThreat(me, 1.0f);
            me->AddThreat(summoned, 1.0f);
            summoned->AI()->AttackStart(me);
            summoned->SetSpeed(MOVE_WALK, 0.5f, true);
            summoned->SetSpeed(MOVE_RUN, 0.4f, true);
```

adding this will solve the issue
