### ISSUE TITLE
Q12244\Q12270 Shredder Repair-Shred the Alliance

### ISSUE THREAD

**Issue by Rog360** [scriptdev2/scriptdev2#165]
You click on C27354[Broken-down Shredder]. Mount it and bring it back to C27371[Synipus] for alliance and C27423[Grekk]for horde.
Not to sure about all the spells below... :)

Spells ?
     48533 Ride Shredder
     48610 Shredder Delivery
     48617 Despawn Shredder

Shred the Alliance Q12270
     https://www.youtube.com/watch?v=3f7YbxnKo6I
	 
Shredder Repair	Q12244
     https://www.youtube.com/watch?v=vtJJzzvvzfo

**Comment by xfurry** [comment]
Poke @grz3s
I think this requires some npc spellclick in order to board the vehicle. Any details would be appreciated.

**Comment by Grz3s** [comment]
done.

**Comment by xfurry** [comment]
> done.

Done -> entire quest? Or do I still need to add something in SD2?

**Comment by Grz3s** [comment]
whole quest is completed.

**Comment by Rog360** [comment]
Thanks Grz3s... :)

**Comment by xfurry** [comment]
Works fine. Issue fixed
