### ISSUE TITLE
Q12726 Song of Wind and Water

### ISSUE THREAD

**Issue by Rog360** [scriptdev2/scriptdev2#167]
You to use the Tempest Drums[I39571] at the Stormwright's Shelf and help Haiphoon[C28999] devour 3 Storm Revenants[C28858] and 3 Aqueous Spirits[C28862]. I can ride Haiphoon with db fix. But only one spell works... :)

Spells
61375 Water Bolt [invalid target]
61376 Frost Nova [Casts OK]
52862 Devour Wind [Doesn't become active]
52864 Devour Water [Doesn't become active]

Video
https://www.youtube.com/watch?v=XbzZq5DLuZg

**Comment by xfurry** [comment]
I thought that this is already fixed: https://github.com/scriptdev2/scriptdev2/issues/82

Are there still issues on this?

**Comment by Rog360** [comment]
I thought so too. But spells not working again. Something change in core? Not sure why it stopped working.. :)

**Comment by xfurry** [comment]
I really can't understand what is wrong with this. I just tested, and it works perfectly fine.

Are you testing on 3.x or 4.x?
Which spells are not working? Summoning the vehicle, or the kill credit spells?

**Comment by xfurry** [comment]
@Rog360 any updates?

**Comment by Rog360** [comment]
Using 3.3.5. I'll check this one again and post back asap... :)

**Comment by xfurry** [comment]
@Rog360 any updates? I'm anxious to close this ticket as I can't replicate it. :wink:

**Comment by Grz3s** [comment]
@xfurry 
just looked at this quest... and can confirm what Rog360 said...
```quote
Spells
 61375 Water Bolt [invalid target]
 61376 Frost Nova [Casts OK]
 52862 Devour Wind [Doesn't become active]
 52864 Devour Water [Doesn't become active]
```
Reason for this is simple.. (i spoke with you about it already) ...
Our Vehicle.. has faction = 35 friendly..
Should change faction to player/npc who rides on it.

P.S ...
As i said already 100%(tested by me) of vehicles + Eye of Acherus(minion?) -- should take Riders faction.

**Comment by xfurry** [comment]
For the faction fix, please try this.
This should fix the vehicle thing. I think that Eye of Acherus already has the faction set right (please confirm)

```diff
@@ -540,10 +540,13 @@ void VehicleInfo::ApplySeatMods(Unit* passenger, uint32 seatFlags)
                 }
                 else if (pPlayer->IsWalking() && !pVehicle->IsWalking())
                 {
                     ((Creature*)pVehicle)->SetWalk(true, true);
                 }
+
+                // set vehicle faction as per the controller faction
+                ((Creature*)pVehicle)->SetFactionTemporary(pPlayer->getFaction(), TEMPFACTION_NONE);
             }
         }
 
         if (seatFlags & SEAT_FLAG_CAN_CAST)
         {
@@ -596,10 +599,14 @@ void VehicleInfo::RemoveSeatMods(Unit* passenger, uint32 seatFlags)
             pVehicle->clearUnitState(UNIT_STAT_CONTROLLED);
             pVehicle->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_PLAYER_CONTROLLED);
 
             // must be called after movement control unapplying
             pPlayer->GetCamera().ResetView();
+
+            // reset vehicle faction
+            if (pVehicle->GetTypeId() == TYPEID_UNIT)
+                ((Creature*)pVehicle)->ClearTemporaryFaction();
         }
 
         if (seatFlags & SEAT_FLAG_CAN_CAST)
             pPlayer->RemovePetActionBar();
     }

```

Spells 52862 and 52864 become active when target is below 30% so I think it works fine.
The other two spells also work fine (maybe it's due to the patch above).

**Comment by Grz3s** [comment]
@xfurry 
this patch is briliant...
fixes .. above quest...
also fixes another vehicles like: Refurbished Shredder etc...
:+1: 

p.s yes eye of acherus works fine..forgot when it was fixed ehh... ;)

**Comment by Rog360** [comment]
Thank you both for fixing this one. I got tied up in real life, But should be back to work soon... :)
