### ISSUE TITLE
Ghostly and Spectral Citizen in Stratholme

### ISSUE THREAD

**Issue by Tobschinski** [scriptdev2/scriptdev2#170]
[Spectral Citizen](http://www.wowhead.com/npc=10384/spectral-citizen) and [Ghostly Citizen](http://www.wowhead.com/npc=10385/ghostly-citizen) have a high chance to dodge an incoming attack if they are in combat.

So please add spell 16331 - Incorporeal Defense (on aggro).

(As always, I have no idea if this spell is known to the client in TBC and WotLK - it is in Classic)

**Comment by xfurry** [comment]
Well, spell 16331 doesn't exist after 2.x

**Comment by evil-at-wow** [comment]
Agreed, that spell doesn't seem to exist. But yet, the crazy amount of dodge was still present in at least TBC and early WoTLK versions! But I'll have to check my Stratholme sniffs to see if I can find out how it was done though...

**Comment by Tobschinski** [comment]
Sadly, the client is never informed about the spell, so I think we can't look at sniffs.

The only reason I noticed that this cast should happen was a closer look at Blizzard's Dungeon Journal. It's mentioned there.

**Comment by xfurry** [comment]
Well, we can force the npc to use the same logic as the missing spell.

The problem is that the SPELL_AURA_MOD_DODGE_PERCENT applies only to players, so I have no idea how to make this work for Units.

**Comment by evil-at-wow** [comment]
> The problem is that the SPELL_AURA_MOD_DODGE_PERCENT applies only to players

You mean that is the current situation in the core, right? And not that this is actually what it should do?

Because there seem to be spells with SPELL_AURA_MOD_DODGE_PERCENT that are used by NPCs (like [54657](http://www.wowhead.com/spell=54657)).

**Comment by xfurry** [comment]
I mean that this is the current core implementation.
If we need this for creatures, we need to update the core.
