### ISSUE TITLE
UBRS Blackrock Stadium Event

### ISSUE THREAD

**Issue by tarwyn** [scriptdev2/scriptdev2#179]
This event spawns several waves of mobs that need to be killed. Once they are all killed the boss will spawn and needs to be killed.

This seems to work essentially but there's a problem:

A wave (of mobs) spawns and the gate opens. The wave moves into the room, up until it's about level with Lord Victor Nefarius and then turns around and walks back to where it spawned, behind the gate, which will be lowering itself. 

If the raid is hanging back at the entrance, there's a good chance the wave will move out of reach behind the gates before it can be killed. This can subsequently break the event.

Correct behaviour:
The wave must walk almost all the way to the back (entrance) of the stadium and then stay there/switch to random movement for each mob in the wave.

**Comment by xfurry** [comment]
@cala can you please confirm is you already fixed this in your commits?
Thanks!

**Comment by Lumber-Jack-2** [comment]
UBRS != BRD

**Comment by xfurry** [comment]
> UBRS != BRD

You are right. Sorry.

I think this might be related to the movement type of the npcs in DB. It should be 0 (idle)
@tarwyn  Can you please check, as I can't replicate the issue on my end.

**Comment by cala** [comment]
> I think this might be related to the movement type of the npcs in DB. It should be 0 (idle)

I would agree. @tarwyn is this issue in WotLK, TBC or Classic?

**Comment by xfurry** [comment]
I will close the issue because there is no feedback.
@tarwyn if you have any updates, please feel free to reopen it, or create a new one.
