### ISSUE TITLE
[TBC/WotLK] Someone Else's Hard Work Pays Off - Escort quest

### ISSUE THREAD

**Issue by Grz3s** [scriptdev2/scriptdev2#180]
Hi
We missing escort q.10218. 'Someone Else's Hard Work Pays Off' in Mana Tombs.
http://www.wowhead.com/quest=10218/someone-elses-hard-work-pays-off
quest was removed with 4.x.x so its difficult to find source, but we have smth.
https://www.youtube.com/watch?v=zehDrQxGyww
https://www.youtube.com/watch?v=5xXlRJg9RXg  -- starts at 4:19

I just fixed prev quest:
https://github.com/unified-db/Database/commit/e588f8e5c7225d0b758a768d0dc21c3b70e721ae
so: our quest giver will be spawn with timer = 2hrs. (main escorted npc is summoned)

Also:
Pls use this spell as his spawn effect = 34427
also got his first text
"This should't take very long. Just watch my back as I empty these nether collectors."

Pls let me know if there will be more difficulties with reading other texts :) ill try to help.
Gl.

**Comment by xfurry** [comment]
> Pls let me know if there will be more difficulties with reading other texts :) ill try to help.

It would be nice if you can find the text yelled by this guy: http://www.wowhead.com/npc=19666/shadow-lord-xiraxis
and the spells that he and http://www.wowhead.com/npc=19671/cryo-engineer-shaheen are using.

**Comment by xfurry** [comment]
Actually I found more info: http://wowwiki.wikia.com/wiki/Quest:Someone_Else%27s_Hard_Work_Pays_Off
