### ISSUE TITLE
Darkshore.cpp Multilanguage Support

### ISSUE THREAD

**Issue by Tauriella** [scriptdev2/scriptdev2#183]
@xfurry can you please in darkshore.cpp an text converting to the MySQL DB please?
thx

```
*####
# npc_threshwackonator
####*/

enum
{
    EMOTE_START             = -1000325,
    SAY_AT_CLOSE            = -1000326,
    QUEST_GYROMAST_REV      = 2078,
    NPC_GELKAK              = 6667,
    FACTION_HOSTILE         = 14
};

#define GOSSIP_ITEM_INSERT_KEY  "[PH] Insert key"

struct npc_threshwackonatorAI : public FollowerAI
{
    npc_threshwackonatorAI(Creature* pCreature) : FollowerAI(pCreature) { Reset(); }

    void Reset() override {}

    void MoveInLineOfSight(Unit* pWho) override
    {
        FollowerAI::MoveInLineOfSight(pWho);

        if (!m_creature->getVictim() && !HasFollowState(STATE_FOLLOW_COMPLETE) && pWho->GetEntry() == NPC_GELKAK)
        {
            if (m_creature->IsWithinDistInMap(pWho, 10.0f))
            {
                DoScriptText(SAY_AT_CLOSE, pWho);
                DoAtEnd();
            }
        }
    }

    void DoAtEnd()
    {
        m_creature->SetFactionTemporary(FACTION_HOSTILE, TEMPFACTION_RESTORE_RESPAWN);

        if (Player* pHolder = GetLeaderForFollower())
            m_creature->AI()->AttackStart(pHolder);

        SetFollowComplete();
    }
};
```

**Comment by xfurry** [comment]
Poke @grz3s about the gossip text.
Need to confirm if that is right

**Comment by Grz3s** [comment]
hi @xfurry 
DB is missing gossip id - for both of his gossips... so if you could do it here, it would be nice...
--
C.6669 should have a 2 gossips:
- 1st. default
textid (from npc_text) = 718
- 2nd, only if player has a key.. "gyromast's key"
textid (from npc_text) = 758
and white option here like your ""[PH] Insert key", but text should be diff.
"Turn the key to start the machine."

And here proof:
https://www.youtube.com/watch?v=8zTGDNvFjYU    3:09

hope it helps ;)

**Comment by Grz3s** [comment]
Hi @xfurry

## DB is missing menu_ids for both of his gossips.. so if you could do it here, it would be nice

C.6669 should have a 2 gossips:
- 1st. default
  textid (from npc_text) = 718
- 2nd, only if player has a key.. "gyromast's key"
  textid (from npc_text) = 758
  and white option here like your ""[PH] Insert key", but text should be diff.
  "Turn the key to start the machine."

And here proof:
https://www.youtube.com/watch?v=8zTGDNvFjYU    3:09

hope it helps ;)
