### ISSUE TITLE
quest 9303

### ISSUE THREAD

**Issue by Grz3s** [scriptdev2/scriptdev2#185]
Quest 9303 Inoculation
http://www.wowhead.com/quest=9303/inoculation

Uses: spell_script for creature 16518   (spell_scripts.cpp)

``` code
        case SPELL_INOCULATE_OWLKIN:
        {
            if (uiEffIndex == EFFECT_INDEX_0)
            {
                if (pCreatureTarget->GetEntry() != NPC_OWLKIN)
                    return true;

                pCreatureTarget->UpdateEntry(NPC_OWLKIN_INOC);
                ((Player*)pCaster)->KilledMonsterCredit(NPC_OWLKIN_INOC);

                // set despawn timer, since we want to remove creature after a short time
                pCreatureTarget->ForcedDespawn(15000);

                return true;
            }
            return true;
        }
```

few problems with this script:

1st:  (critical)
casting spell on c16518 with MovementType = 0 script will go fine.. but after creature respawn
We'll recive neverending spam on console:
"ERROR:Map::GetReachableRandomPosition> Unsupported unit type is passed!"
Using spell on c16518  with MovementType = 1, problem wont happen.

2nd:
new entry 16534 ( NPC_OWLKIN_INOC) -- will never use his EAI (should do random textemote)
also:
found small typo in one of his random texts:
EAI:

``` sql
('-909','The %s doen\'t look like it minds the crystal\'s effect.','0','2','0','16534','22'), -- need fix "doen\'t" --> should be "doesn\'t"
```

vid:
https://www.youtube.com/watch?v=pGiWRvY8ut0
thx

**Comment by xfurry** [comment]
@Grz3s for the 2nd problem please try this:

``` sql
-- Creature id: 16534
UPDATE creature_template SET AIName='EventAI' WHERE entry=16534;
DELETE FROM creature_ai_scripts WHERE creature_id=16534;
INSERT INTO creature_ai_scripts VALUES 
('1653401','16534','29','0','100','32','1000','1000','0','0','1','-906','-907','-908','1','-909','-910','-906','1','-907','-908','-909','Inoculated Nestlewood Owlkin - Random Text Emote');
```

For the first point, we need to poke @cyberium

**Comment by xfurry** [comment]
@Grz3s 
For first problem you can use this. Although I still think that @cyberium should investigate a possible issue with https://github.com/cmangos/mangos-wotlk/commit/1b07104557529b2a56ed5cbe757f22c285237514

``` sql
UPDATE creature_template SET MovementType=0 WHERE entry=16518;
```
