### ISSUE TITLE
ESCORT quest.9759

### ISSUE THREAD

**Issue by Grz3s** [scriptdev2/scriptdev2#188]
Hi @xfurry 
I collected all data needed for escort quest:
'Ending Their World' q.9759

First pls look at this vid:
https://www.youtube.com/watch?v=lARzK9CLu24
-- theyre lots more -  easy to find on YT.

And here all important data you need here
- important cords where smth happens
- all texts
- all correct spawn points for explosives and fires etc

http://paste2.org/navLWZme

If anything will be complicated to read ... ill help :)
END quest event i already finished using dbscripts_on_quest_end ... so only escort itself is needed ;)
GL.

BTW:
Pls dont forget about Sironas
https://github.com/unified-db/Database/issues/73#issuecomment-210132623
She is part of this quest

**Comment by xfurry** [comment]
@Grz3s any idea what spell is http://www.wowhead.com/npc=17678/sironas using to transform / scale up?

PS.
I'm not sure why you gave me the coords of the gameobjects in your data. Do I need to use those anywhere?

**Comment by Grz3s** [comment]
``` quote
@Grz3s any idea what spell is http://www.wowhead.com/npc=17678/sironas using to transform / scale up?
```

I'll check that ...

``` quote
I'm not sure why you gave me the coords of the gameobjects in your data. Do I need to use those anywhere?
```

yes... look at that avi ... u'll see:
4:03 -- he spawns first 5   - 182088 'Draenei Explosives'   -- You can see explosion at 4:47
4:50 --  first group of fires is spawned
than:
7:50 -- second group of 'Draenei Explosives' is spawned
after explosion -- second group of fires is spawned

I gave you all of them -- because i dont know if you want to add 'em by sd2 or i should add them in db with negative resp time -- so sd2 will only do respawn. (let me know what is better for you)

I have my own vid... but is in 5 or 6 parts
pls look at this one. you should be able to see first set of barrows spawned.. ;)
https://youtu.be/Z4ZZFiLCdgU

**Comment by xfurry** [comment]
> I gave you all of them -- because i dont know if you want to add 'em by sd2 or i should add them in db with negative resp time -- so sd2 will only do respawn. (let me know what is better for you)

Unless there is a summon spell for these (which I doubt), we need to add them to the DB with negative spawn times, and SD2 will respawn them.

**Comment by Grz3s** [comment]
ok ... so i'll add them all and will give you all guids... ;)

**Comment by Grz3s** [comment]
``` quote
@Grz3s any idea what spell is http://www.wowhead.com/npc=17678/sironas using to transform / scale up?
I'll check that ...
```

No spell shows in sniff ... only size update 

``` code
ServerToClient: SMSG_UPDATE_OBJECT (0x277D) Length: 75 ConnIdx: 1 NumObjUpdates: 1
MapID: 530 (530)
HasDestroyObjects: False
Data size: 64
[0] UpdateType: Values
[0] Object Guid: Full: 0x2009E442401143800000250000000A8E Creature Map: 530 Entry: 17678 Low: 2702
[0] OBJECT_FIELD_SCALE_X: 1073741824/2
[0] UNIT_FIELD_BOUNDINGRADIUS: 1065916595/1.06716
[0] UNIT_FIELD_COMBATREACH: 1077936128/3
[0] UNIT_FIELD_SCALE_DURATION: 2000/2.802597E-42
```

I also looked at all spells with:
SPELL_AURA_MOD_SCALE

only one spell change her size to same one what we see on vid:
ID - 22735 Spirit of Runn Tum
Aura Id 61 (SPELL_AURA_MOD_SCALE), value = 300, misc = 0 (0), miscB = 0, periodic = 0
Spell is not from this npc -- but i cant see any other.
