### ISSUE TITLE
Nightbane

### ISSUE THREAD

**Issue by overy** [scriptdev2/scriptdev2#69]
TBC: 84d1ee6c89d7a26471ada731b294b7bb902bfcf0
SD:9e4e21d344a937bdd780f16d7ec7e966ae2e58dc
DB: 1.4.0

Hi, there are problem when nightbane change phase from air to ground. When someone get higgest threat then tank, nightbane stuck in air. The same way is when you try it with mage and cast Ice block.

**Comment by xfurry** [comment]
If you still got problems with this boss, please open a new ticket with the details.
