### ISSUE TITLE
[Compile x64] Error VC100

### ISSUE THREAD

**Issue by Angarius** [scriptdev2/scriptdev2#7]
Hello Scriptdev2 Team,

I have tried to compile your scripts under Windows x64 on the way which you gave us in the DOCs -> How to install
MS Windows:
- Compile ScriptDev2 using the scriptVC80, scriptVC90 or scriptVC100 Solution within the ScriptDev2 folder (this will overwrite the Mangoscript dll in the output directory)

The Version of commit which I have taken:
1d33dfd3414b69e178176b47062fe9c12f1ebd8e

My try to compile with VC100:

The build process was launched on 1/11/2012 1:15:07 AM.
      1> Project "C: \ Users \ user \ git \ ScriptDev2 \ VC100 \ 100ScriptDev2.vcxproj" on node "2", build target (s).
      1> InitializeBuildStatus:
          ". \ ScriptDev2__x64_Release \ ScriptDev2.unsuccessfulbuild" is created because "always create" is specified.
        Custom build:
          Extracting revision
          The system can not find the path specified.
      1> C: \ Program Files (x86) \ MSBuild \ Microsoft.Cpp \ v4.0 \ Microsoft.CppCommon.targets (151.5): error MSB6006: "cmd.exe" exited with code 3.
      1> The creation of the project "C: \ Users \ user \ git \ ScriptDev2 \ VC100 \ 100ScriptDev2.vcxproj" is complete, build target (s) - DEFECTS.

Failed to build

Elapsed time 00:00:00.24

Maybe you can help us.
Thank you
- Angarius

**Comment by unknownbboy** [comment]
i have this problem too .. 

1>------ Build started: Project: ScriptDev2, Configuration: Release Win32 ------
1>  Extracting revision
1>  The system cannot find the path specified.
1>C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(170,5): error MSB6006: "cmd.exe" exited with code 3.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========


how i can fix this issus?

**Comment by evil-at-wow** [comment]
It sounds like you're missing the 'genrevision' binary, which should be built when you build the core. You can easily (re)build the 'genrevision' project: open the core's Visual Studio solution - win/mangosdVC120.sln - and then just switch to the genrevision project and build that one (make sure to build the release-Win32 target). Then build ScriptDev2 again.

**Comment by unknownbboy** [comment]
i try but again show new problem : 
1>------ Build started: Project: ScriptDev2, Configuration: Release Win32 ------
1>C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(170,5): error MSB6003: The specified task executable "cmd.exe" could not be run. Insufficient system resources exist to complete the requested service
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by xfurry** [comment]
Let me understand. Are you trying to build for win32 or win64?

**Comment by Ulduar** [comment]
``` QUOTE
Configuration: Release Win32 ------
```
Read.

**Comment by unknownbboy** [comment]
win32

**Comment by unknownbboy** [comment]
evil-at-wow  , i try you'r help sir! 
but again show this error! how can i fix this Problem?

**Comment by evil-at-wow** [comment]
I don't know. This sounds like you have an issue with Visual Studio or the system itself. For some reason cmd.exe (the Windows command line interpreter) can't be started, apparently because there are insufficient system resources. I can't imagine that you would use a recent Visual Studio version on a system that's old or doesn't have a lot of memory...

Maybe there is something weird in the project after all, but I can't test that right now because I don't have a Windows system here.

**Comment by unknownbboy** [comment]
hmh, yes maybe my windows have problems! 
latter i change and test it!

thank you for answer!

**Comment by unknownbboy** [comment]
sir i change the somethings and works fine! but now i have a diffrent problem :-1: 

1>------ Build started: Project: ScriptDev2, Configuration: Release Win32 ------
1>  Extracting revision
1>  precompiled.cpp
1>  escort_ai.cpp
1>..\base\escort_ai.cpp(40): error C2039: 'GetWaypointPathInformation' : is not a member of 'MotionMaster'
1>          m:\server\tbc\project ava wow [coronacore]\funserver\gitlab-oneserver\src\game\MotionMaster.h(61) : see declaration of 'MotionMaster'
1>..\base\escort_ai.cpp(232): error C2065: 'EXTERNAL_WAYPOINT_MOVE' : undeclared identifier
1>..\base\escort_ai.cpp(237): error C2065: 'EXTERNAL_WAYPOINT_MOVE_START' : undeclared identifier
1>..\base\escort_ai.cpp(239): error C2065: 'EXTERNAL_WAYPOINT_FINISHED_LAST' : undeclared identifier
1>..\base\escort_ai.cpp(261): error C2039: 'SetNextWaypoint' : is not a member of 'MotionMaster'
1>          m:\server\tbc\project ava wow [coronacore]\funserver\gitlab-oneserver\src\game\MotionMaster.h(61) : see declaration of 'MotionMaster'
1>..\base\escort_ai.cpp(332): error C2660: 'MotionMaster::MoveWaypoint' : function does not take 3 arguments
1>  follower_ai.cpp
1>  guard_ai.cpp
1>  pet_ai.cpp
1>  battleground.cpp
1>  alterac_mountains.cpp
1>  arathi_highlands.cpp
1>  blasted_lands.cpp
1>  burning_steppes.cpp
1>  dun_morogh.cpp
1>  eastern_plaguelands.cpp
1>  elwynn_forest.cpp
1>  eversong_woods.cpp
1>  ghostlands.cpp
1>  hinterlands.cpp
1>  ironforge.cpp
1>  isle_of_queldanas.cpp
1>  loch_modan.cpp
1>  redridge_mountains.cpp
1>  searing_gorge.cpp
1>  Generating Code...
1>  Compiling...
1>  silvermoon_city.cpp
1>  silverpine_forest.cpp
1>  stormwind_city.cpp
1>  stranglethorn_vale.cpp
1>  swamp_of_sorrows.cpp
1>  tirisfal_glades.cpp
1>  undercity.cpp
1>  western_plaguelands.cpp
1>  westfall.cpp
1>  wetlands.cpp
1>  blackrock_depths.cpp
1>  boss_ambassador_flamelash.cpp
1>  boss_coren_direbrew.cpp
1>  boss_emperor_dagran_thaurissan.cpp
1>  boss_general_angerforge.cpp
1>  boss_high_interrogator_gerstahn.cpp
1>  instance_blackrock_depths.cpp
1>  boss_gyth.cpp
1>m:\server\tbc\project ava wow [coronacore]\funserver\gitlab-oneserver\src\bindings\onescripts\scripts\eastern_kingdoms\blackrock_spire\blackrock_spire.h(123): error C3668: 'instance_blackrock_spire::OnCreatureDespawn' : method with override specifier 'override' did not override any base class methods
1>  boss_overlord_wyrmthalak.cpp
1>  boss_pyroguard_emberseer.cpp
1>m:\server\tbc\project ava wow [coronacore]\funserver\gitlab-oneserver\src\bindings\onescripts\scripts\eastern_kingdoms\blackrock_spire\blackrock_spire.h(123): error C3668: 'instance_blackrock_spire::OnCreatureDespawn' : method with override specifier 'override' did not override any base class methods
1>  Generating Code...
1>  Compiling...
1>  instance_blackrock_spire.cpp
1>m:\server\tbc\project ava wow [coronacore]\funserver\gitlab-oneserver\src\bindings\onescripts\scripts\eastern_kingdoms\blackrock_spire\blackrock_spire.h(123): error C3668: 'instance_blackrock_spire::OnCreatureDespawn' : method with override specifier 'override' did not override any base class methods
1>  boss_broodlord_lashlayer.cpp
1>  boss_chromaggus.cpp
1>  boss_ebonroc.cpp
1>  boss_firemaw.cpp
1>  boss_flamegor.cpp
1>  boss_nefarian.cpp
1>  boss_razorgore.cpp
1>  boss_vaelastrasz.cpp
1>  boss_victor_nefarius.cpp
1>..\scripts\eastern_kingdoms\blackwing_lair\boss_victor_nefarius.cpp(190): error C2065: 'UNIT_BYTE1_FLAG_FLY_ANIM' : undeclared identifier
1>  instance_blackwing_lair.cpp
1>  boss_mr_smite.cpp
1>  deadmines.cpp
1>  instance_deadmines.cpp
1>  boss_thermaplugg.cpp
1>  gnomeregan.cpp
1>  instance_gnomeregan.cpp
1>  boss_curator.cpp
1>  boss_maiden_of_virtue.cpp
1>  boss_midnight.cpp
1>  Generating Code...
1>  Compiling...
1>  boss_moroes.cpp
1>  boss_netherspite.cpp
1>  boss_nightbane.cpp
1>..\scripts\eastern_kingdoms\karazhan\boss_nightbane.cpp(142): error C2065: 'UNIT_BYTE1_FLAG_FLY_ANIM' : undeclared identifier
1>..\scripts\eastern_kingdoms\karazhan\boss_nightbane.cpp(164): error C2065: 'UNIT_BYTE1_FLAG_FLY_ANIM' : undeclared identifier
1>..\scripts\eastern_kingdoms\karazhan\boss_nightbane.cpp(267): error C2065: 'UNIT_BYTE1_FLAG_FLY_ANIM' : undeclared identifier
1>..\scripts\eastern_kingdoms\karazhan\boss_nightbane.cpp(374): error C2065: 'UNIT_BYTE1_FLAG_FLY_ANIM' : undeclared identifier
1>  boss_prince_malchezaar.cpp
1>  boss_shade_of_aran.cpp
1>  boss_terestian_illhoof.cpp
1>  bosses_opera.cpp
1>  chess_event.cpp
1>  instance_karazhan.cpp
1>  karazhan.cpp
1>..\scripts\eastern_kingdoms\karazhan\karazhan.cpp(385): error C2065: 'UNIT_BYTE1_FLAG_FLY_ANIM' : undeclared identifier
1>  boss_felblood_kaelthas.cpp
1>  boss_priestess_delrissa.cpp
1>  boss_selin_fireheart.cpp
1>  boss_vexallus.cpp
1>  instance_magisters_terrace.cpp
1>  magisters_terrace.cpp
1>  boss_baron_geddon.cpp
1>  boss_garr.cpp
1>  boss_gehennas.cpp
1>  boss_golemagg.cpp
1>  Generating Code...
1>  Compiling...
1>  boss_lucifron.cpp
1>  boss_magmadar.cpp
1>  boss_majordomo_executus.cpp
1>  boss_ragnaros.cpp
1>  boss_shazzrah.cpp
1>  boss_sulfuron_harbinger.cpp
1>  instance_molten_core.cpp
1>  molten_core.cpp
1>  boss_anubrekhan.cpp
1>  boss_faerlina.cpp
1>  boss_four_horsemen.cpp
1>  boss_gluth.cpp
1>  boss_gothik.cpp
1>  boss_grobbulus.cpp
1>  boss_heigan.cpp
1>  boss_kelthuzad.cpp
1>  boss_loatheb.cpp
1>  boss_maexxna.cpp
1>  boss_noth.cpp
1>  boss_patchwerk.cpp
1>  Generating Code...
1>  Compiling...
1>  boss_razuvious.cpp
1>  boss_sapphiron.cpp
1>  boss_thaddius.cpp
1>  instance_naxxramas.cpp
1>  boss_arcanist_doan.cpp
1>  boss_headless_horseman.cpp
1>  boss_herod.cpp
1>  boss_mograine_and_whitemane.cpp
1>  instance_scarlet_monastery.cpp
1>  boss_darkmaster_gandling.cpp
1>  boss_jandice_barov.cpp
1>  instance_scholomance.cpp
1>  instance_shadowfang_keep.cpp
1>  shadowfang_keep.cpp
1>  boss_baroness_anastari.cpp
1>  boss_cannon_master_willey.cpp
1>  boss_dathrohan_balnazzar.cpp
1>  boss_maleki_the_pallid.cpp
1>  boss_order_of_silver_hand.cpp
1>  instance_stratholme.cpp
1>  Generating Code...
1>  Compiling...
1>  stratholme.cpp
1>  instance_sunken_temple.cpp
1>  sunken_temple.cpp
1>  boss_brutallus.cpp
1>  boss_eredar_twins.cpp
1>  boss_felmyst.cpp
1>  boss_kalecgos.cpp
1>..\scripts\eastern_kingdoms\sunwell_plateau\boss_kalecgos.cpp(226): error C2065: 'UNIT_BYTE1_FLAG_FLY_ANIM' : undeclared identifier
1>  boss_kiljaeden.cpp
1>  boss_muru.cpp
1>  instance_sunwell_plateau.cpp
1>  boss_archaedas.cpp
1>  uldaman.cpp
1>  instance_uldaman.cpp
1>  boss_akilzon.cpp
1>  boss_halazzi.cpp
1>  boss_janalai.cpp
1>  boss_malacrass.cpp
1>  boss_nalorakk.cpp
1>  boss_zuljin.cpp
1>  instance_zulaman.cpp
1>  Generating Code...
1>  Compiling...
1>  zulaman.cpp
1>  boss_arlokk.cpp
1>  boss_hakkar.cpp
1>  boss_hazzarah.cpp
1>  boss_jeklik.cpp
1>  boss_jindo.cpp
1>  boss_mandokir.cpp
1>  boss_marli.cpp
1>  boss_renataki.cpp
1>  boss_thekal.cpp
1>  boss_venoxis.cpp
1>  instance_zulgurub.cpp
1>  example_creature.cpp
1>  example_escort.cpp
1>  example_gossip_codebox.cpp
1>  example_misc.cpp
1>  ashenvale.cpp
1>  azshara.cpp
1>  azuremyst_isle.cpp
1>  bloodmyst_isle.cpp
1>  Generating Code...
1>  Compiling...
1>  boss_azuregos.cpp
1>  darkshore.cpp
1>  desolace.cpp
1>  durotar.cpp
1>  dustwallow_marsh.cpp
1>..\scripts\kalimdor\dustwallow_marsh.cpp(859): error C2039: 'SetSwim' : is not a member of 'Creature'
1>          M:\Server\TBC\Project Ava WoW [CoronaCore]\funserver\gitlab-oneserver\src\game\Creature.h(487) : see declaration of 'Creature'
1>  felwood.cpp
1>  feralas.cpp
1>  moonglade.cpp
1>  mulgore.cpp
1>  orgrimmar.cpp
1>  silithus.cpp
1>..\scripts\kalimdor\silithus.cpp(305): error C2065: 'UNIT_BYTE1_FLAG_FLY_ANIM' : undeclared identifier
1>..\scripts\kalimdor\silithus.cpp(323): error C2065: 'UNIT_BYTE1_FLAG_FLY_ANIM' : undeclared identifier
1>..\scripts\kalimdor\silithus.cpp(352): error C2065: 'UNIT_BYTE1_FLAG_FLY_ANIM' : undeclared identifier
1>..\scripts\kalimdor\silithus.cpp(631): error C2065: 'UNIT_BYTE1_FLAG_FLY_ANIM' : undeclared identifier
1>  stonetalon_mountains.cpp
1>  tanaris.cpp
1>  teldrassil.cpp
1>  the_barrens.cpp
1>  thousand_needles.cpp
1>  thunder_bluff.cpp
1>  ungoro_crater.cpp
1>  winterspring.cpp
1>  instance_blackfathom_deeps.cpp
1>  Generating Code...
1>  Compiling...
1>  boss_aeonus.cpp
1>  boss_chrono_lord_deja.cpp
1>  boss_temporus.cpp
1>  dark_portal.cpp
1>  instance_dark_portal.cpp
1>  boss_archimonde.cpp
1>  hyjal.cpp
1>  hyjalAI.cpp
1>  instance_hyjal.cpp
1>  instance_old_hillsbrad.cpp
1>  old_hillsbrad.cpp
1>  dire_maul.cpp
1>  instance_dire_maul.cpp
1>  boss_noxxion.cpp
1>  boss_onyxia.cpp
1>..\scripts\kalimdor\onyxias_lair\boss_onyxia.cpp(249): error C2065: 'UNIT_BYTE1_FLAG_FLY_ANIM' : undeclared identifier
1>  instance_onyxias_lair.cpp
1>  instance_razorfen_downs.cpp
1>  razorfen_downs.cpp
1>  instance_razorfen_kraul.cpp
1>  razorfen_kraul.cpp
1>  Generating Code...
1>  Compiling...
1>  boss_ayamiss.cpp
1>  boss_buru.cpp
1>  boss_kurinnaxx.cpp
1>  boss_moam.cpp
1>  boss_ossirian.cpp
1>..\scripts\kalimdor\ruins_of_ahnqiraj\boss_ossirian.cpp(108): error C2039: 'SetWeather' : is not a member of 'Map'
1>          m:\server\tbc\project ava wow [coronacore]\funserver\gitlab-oneserver\src\game\Map.h(98) : see declaration of 'Map'
1>  boss_rajaxx.cpp
1>  instance_ruins_of_ahnqiraj.cpp
1>  ruins_of_ahnqiraj.cpp
1>  boss_bug_trio.cpp
1>  boss_cthun.cpp
1>  boss_fankriss.cpp
1>  boss_huhuran.cpp
1>  boss_ouro.cpp
1>  boss_sartura.cpp
1>  boss_skeram.cpp
1>  boss_twinemperors.cpp
1>  boss_viscidus.cpp
1>  instance_temple_of_ahnqiraj.cpp
1>  mob_anubisath_sentinel.cpp
1>  instance_wailing_caverns.cpp
1>  Generating Code...
1>  Compiling...
1>  wailing_caverns.cpp
1>..\scripts\kalimdor\wailing_caverns\wailing_caverns.cpp(391): error C2065: 'UNIT_BYTE1_FLAG_FLY_ANIM' : undeclared identifier
1>  boss_zumrah.cpp
1>  instance_zulfarrak.cpp
1>  zulfarrak.cpp
1>  blades_edge_mountains.cpp
1>..\scripts\outland\blades_edge_mountains.cpp(161): error C2065: 'UNIT_BYTE1_FLAG_FLY_ANIM' : undeclared identifier
1>  boss_doomlord_kazzak.cpp
1>  boss_doomwalker.cpp
1>  hellfire_peninsula.cpp
1>  nagrand.cpp
1>  netherstorm.cpp
1>  shadowmoon_valley.cpp
1>..\scripts\outland\shadowmoon_valley.cpp(102): error C2065: 'UNIT_BYTE1_FLAG_FLY_ANIM' : undeclared identifier
1>..\scripts\outland\shadowmoon_valley.cpp(144): error C2065: 'UNIT_BYTE1_FLAG_FLY_ANIM' : undeclared identifier
1>  shattrath_city.cpp
1>  terokkar_forest.cpp
1>  zangarmarsh.cpp
1>  boss_exarch_maladaar.cpp
1>  boss_shirrak.cpp
1>  boss_nexusprince_shaffar.cpp
1>  boss_pandemonius.cpp
1>  boss_anzu.cpp
1>  boss_darkweaver_syth.cpp
1>  Generating Code...
1>  Compiling...
1>  boss_talon_king_ikiss.cpp
1>  instance_sethekk_halls.cpp
1>  boss_ambassador_hellmaw.cpp
1>  boss_blackheart_the_inciter.cpp
1>  boss_grandmaster_vorpil.cpp
1>  boss_murmur.cpp
1>  instance_shadow_labyrinth.cpp
1>  black_temple.cpp
1>  boss_bloodboil.cpp
1>  boss_illidan.cpp
1>  boss_mother_shahraz.cpp
1>  boss_reliquary_of_souls.cpp
1>  boss_shade_of_akama.cpp
1>  boss_supremus.cpp
1>  boss_teron_gorefiend.cpp
1>  boss_warlord_najentus.cpp
1>  illidari_council.cpp
1>  instance_black_temple.cpp
1>  boss_fathomlord_karathress.cpp
1>  boss_hydross_the_unstable.cpp
1>  Generating Code...
1>  Compiling...
1>  boss_lady_vashj.cpp
1>  boss_leotheras_the_blind.cpp
1>  boss_morogrim_tidewalker.cpp
1>  boss_the_lurker_below.cpp
1>..\scripts\outland\coilfang_reservoir\serpent_shrine\boss_the_lurker_below.cpp(82): error C2039: 'SetSwim' : is not a member of 'Creature'
1>          M:\Server\TBC\Project Ava WoW [CoronaCore]\funserver\gitlab-oneserver\src\game\Creature.h(487) : see declaration of 'Creature'
1>  instance_serpent_shrine.cpp
1>  boss_ahune.cpp
1>  boss_hydromancer_thespia.cpp
1>  boss_mekgineer_steamrigger.cpp
1>  boss_warlord_kalithresh.cpp
1>  instance_steam_vault.cpp
1>  boss_hungarfen.cpp
1>  boss_gruul.cpp
1>  boss_high_king_maulgar.cpp
1>  instance_gruuls_lair.cpp
1>  boss_broggok.cpp
1>  boss_kelidan_the_breaker.cpp
1>  boss_the_maker.cpp
1>  instance_blood_furnace.cpp
1>  boss_nazan_and_vazruden.cpp
1>..\scripts\outland\hellfire_citadel\hellfire_ramparts\boss_nazan_and_vazruden.cpp(115): error C2065: 'UNIT_BYTE1_FLAG_FLY_ANIM' : undeclared identifier
1>  boss_omor_the_unscarred.cpp
1>  Generating Code...
1>  Compiling...
1>  boss_watchkeeper_gargolmar.cpp
1>  instance_hellfire_ramparts.cpp
1>  boss_magtheridon.cpp
1>  instance_magtheridons_lair.cpp
1>  boss_nethekurse.cpp
1>  boss_warbringer_omrogg.cpp
1>  boss_warchief_kargath_bladefist.cpp
1>  instance_shattered_halls.cpp
1>  arcatraz.cpp
1>  boss_dalliah.cpp
1>  boss_harbinger_skyriss.cpp
1>  boss_soccothrates.cpp
1>  instance_arcatraz.cpp
1>  boss_high_botanist_freywinn.cpp
1>  boss_laj.cpp
1>  boss_warp_splinter.cpp
1>  boss_alar.cpp
1>  boss_astromancer.cpp
1>  boss_kaelthas.cpp
1>  boss_void_reaver.cpp
1>  Generating Code...
1>  Compiling...
1>  instance_the_eye.cpp
1>  boss_nethermancer_sepethrea.cpp
1>  boss_pathaleon_the_calculator.cpp
1>  instance_mechanar.cpp
1>  areatrigger_scripts.cpp
1>  bosses_emerald_dragons.cpp
1>  go_scripts.cpp
1>  guards.cpp
1>  item_scripts.cpp
1>  mob_generic_creature.cpp
1>  npc_professions.cpp
1>  npcs_special.cpp
1>  spell_scripts.cpp
1>  world_map_scripts.cpp
1>  sc_creature.cpp
1>  sc_grid_searchers.cpp
1>  sc_instance.cpp
1>  ScriptLoader.cpp
1>  system.cpp
1>..\system\system.cpp(108): error C3861: 'AddWaypointFromExternal': identifier not found
1>  ScriptMgr.cpp
1>..\ScriptMgr.cpp(48): error C3861: 'SetExternalWaypointTable': identifier not found
1>  Generating Code...
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========


how can i fix this problems ? 
i use : Using World DB: OneDatabase 2.0.1 for MaNGOSOne s2120+ and ScriptDevOne s2783+

but i cant find SD2 for s2783+ version!

**Comment by evil-at-wow** [comment]
You'll have to update your core to a more recent revision. 

In cases like this, it is a good idea to quickly check the git log and see if there's any mention of required revisions. For example, in the log of this project I can find this one:
```
[3097] Use WaypointMovement for Escort-Scripting. Requires CMaNGOS [12839]
```
This means you'll need at least that revision of the core. We're most likely not always mentioning required core revisions, but it's an easy first check to do.

**Comment by unknownbboy** [comment]
thank you for support. underestand now.
