### ISSUE TITLE
Q11876 Help Those That Cannot Help Themselves

### ISSUE THREAD

**Issue by Rog360** [scriptdev2/scriptdev2#78]
The problem with GO not de-spawning after activated. Sorry to put this on you. I got the quest working but this causes all GO [Mammoth Trap 22 count] to be used over and over for quest credit. Also creature should get up and possibly move along. If I'm missing something that makes this possible db side please post. Link below is to Bug Report and my fix. 

http://project-silvermoon.forumotion.com/t320-improvement-quest-11876-help-those-that-cannot-help-themselves#1437

Thanks for your work... :)

**Comment by virusav** [comment]
At this point the quest is realized through the base.
On the part of the core is necessary to implement respawn objects that have been activated and remains in the world.

By SD2 this problem is not related.

**Comment by xfurry** [comment]
you mean:
```
pGo->SetLootState(GO_JUST_DEACTIVATED);
```
as script command?

**Comment by virusav** [comment]
No.
I tried various options, but visually the object remained unchanged.

Respawn object should occur automatically at `spawntimesecs`, ie player activated object sees animation, waiting for `spawntimesecs` - object is returned to its original state.

In this case, after the activation of these objects can not be reactivated.

**Comment by virusav** [comment]
In my understanding, there are the following types of treatment facilities, which can be activated:
1. If `spawntimesecs`> 0:
1.1. After activation remains in the world - through `spawntimesecs` respawn occurs, can not be reactivated to respawn.
1.2. After activation disappears from the world - through `spawntimesecs` respawn occurs, can not be reactivated to respawn.

2. If `spawntimesecs` <0, then the script is being processed.

For Option 1 respawn and ban reactivate must be hardcoded in the core.

For option 2 and option 1 for exceptions (if any) can be added to the command object activation check on the state of the object (active or not).

**Comment by Grz3s** [comment]
https://github.com/unified-db/Database/commit/9d1805bbc746b54529a2a286808fc051e10917c4
if anyone interested.
