### ISSUE TITLE
Escort quest 5944 [In Dreams] 

### ISSUE THREAD

**Issue by Rog360** [scriptdev2/scriptdev2#92]
Too much info to post so I'll post some links. You are under spell 17961 when doing this quest and he is aggressive without it. 
When taking the quest he changes factions and fights scarlet npcs as he makes his way to the tower... :)

http://www.wowhead.com/quest=5944/in-dreams#comments

Good Videos for it.
http://www.youtube.com/watch?v=aHrFZgJt3Zg
http://www.youtube.com/watch?v=zuRVZhAVr70

Wowwiki
http://www.wowwiki.com/Quest:In_Dreams

If you need any more info I'll be right here... :)

**Comment by TheTrueAnimal** [comment]
@xfurry: Fordring can't handle the enemies. He dies within the first minute.

**Comment by xfurry** [comment]
@cala can you please check Fordring's stats (hp, armor, etc...)

**Comment by cala** [comment]
Yes, this is a DB issue. Fordring is missing its armor in Classic DB (idem in UDB) and a few stats need small tweaks.
